import type { NextPage } from 'next'
import Head from 'next/head'
import SideBar from '../components/SideBar'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Whatsapp</title>
                <meta name="description" content="Generated by create lnt" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <SideBar/>
        </div>
    )
}

export default Home
